language: node_js

node_js:
  - iojs-v2

script:
  - make test

notifications:
  slack:
    secure: AuOBG/XLd3byfSLZ0qcb8vr/JZ6KAj+hcRGvXNi3c6vXgARyqGMzyOJLg9kws3Bvzvr89GKNSM0t98Tyq7tL4i0BlXy4Z4TJS3gCoqYX7LJ3iNl8aThO9+wZ+gkcgU7Hc82pBd3bBxvCNnIQ+m6WBzkGd0OswVQon3JlmM44Mpzz2q4M0/ENt7u7Dgwx6dDj2gVijpDpC3eZJrrP4loXjsVH0SuMmmpW9pbgME4Z7pMSpECZDWHe2aO8jssgToAgWGAdQTJ6jApL2umPHHdTToDBEsQSm3K+a0wbYBVs6Vskj2RIS1D294Q4k4a+7sSlZzh1q+T35kFXEwvv6nkrHl6W1uw8E0WWrzpB5+o085IHAO4DrZKksHyZYFlBqU3T3hiws3dUJXDpOCsR7auFf7B3BKEpzrC8OXYCcpb/+KdbJ/amGYP4zizVq0UbcoL3htNdtuyamXOU3GeduTOd3+b57egJohvpTatU23RfYmOKb0mGkXTcDxND3LCqANzSNRUq6J4Aa2K4K3dGDMYPhQvx15/kgIEcgEQ9E5VKUBhE6mmQXS3RVulrY5clueHJ3QTfPiWGMPH85kcVtolhJ0EqsiBo1/zvvNjPfbcmYbkFnNQKO33Qgc4esq2we/D4egwPXNcSkNu8gXgAtJbsmzC7VWNg5RkEhiqKfg8MppI=
